# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo_myname.png"
    alt: "KEG"

### Header
header:
  logo:
    image: "assets/img/logo_myname.png"
    alt: "KEG"

# ### Social
# social:
#   - title: "Twitter"
#     icon: "fab fa-twitter"
#     url: "http://twitter.com"

#   - title: "Dribbble"
#     icon: "fab fa-dribbble"
#     url: "http://dribbble.com"

#   - title: "Behance"
#     icon: "fab fa-behance"
#     url: "http://behance.com"

### Footer
footer:
  developer: "Uigyeol <strong>Kim</strong>"
  copyright: "<strong>기술</strong>. 블로그"

# ### Portfolio Filters Settings
# portfolio:
#   layout: "list" # select works layout options: "Grid" or "List"
#   filters:
#     - name: "Cybersecurity & Forensics"
#       slug: "Cybersecurity & Forensics"

#     - name: "Cryptography & Development"
#       slug: "Cryptography & Development"

#     - name: "UI/UX & Tools"
#       slug: "UI/UX & Tools"
